"""Deliverable 5 - Python Validation Pipeline Evidence (PDF), and
Deliverable 6 - GenAI and Python Comparison Report (PDF + Excel).
    python -m src.evidence.build_validation_evidence            # offline stand-in model for plan generation
    python -m src.evidence.build_validation_evidence --live     # real API from .env (recommended for the final submission)
    python -m src.evidence.build_validation_evidence --rebuild  # re-draw both PDFs from the last capture"""
import json
import os
import subprocess
import sys
from collections import Counter

from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.lib.units import mm
from reportlab.platypus import NextPageTemplate, PageBreak, Spacer, CondPageBreak, Paragraph

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)
from src.evidence.pdfkit import *   # noqa: E402,F401,F403
from src.evidence import capture_validation   # noqa: E402

OUT5 = os.path.join(ROOT, "reports", "Deliverable_5_Python_Validation_Evidence.pdf")
OUT6 = os.path.join(ROOT, "reports", "Deliverable_6_GenAI_vs_Python_Comparison_Report.pdf")
OUT6X = os.path.join(ROOT, "reports", "Deliverable_6_GenAI_vs_Python_Comparison_Report.xlsx")
PW, LW = 174 * mm, 269 * mm
STATUS_KIND = {"Verified": "ok", "Verified with Warning": "info", "Partially Verified": "info", "Requirement Missing": "warn",
               "Source Support Missing": "warn", "Unsupported Requirement": "warn", "Outdated Source": "warn",
               "Contradiction Detected": "warn", "Manual Review Required": "note", "Optional Not Included": "note"}
COLOR = {"ok": "#2b7a53", "info": "#9a6a14", "warn": "#a3372a", "note": "#2a5d8f"}


def badge(status):
    c = COLOR[STATUS_KIND.get(status, "note")]
    return f"<font name='Sans-B' color='{c}'>{esc(status)}</font>"


def delta(before, after, unit="%"):
    d = round(after - before, 1)
    return f"{before}{unit} &rarr; <b>{after}{unit}</b>" + (f" <font color='#a3372a'>({d:+}{unit})</font>" if d else "")


def run_tests(expr):
    try:
        r = subprocess.run([sys.executable, "-m", "pytest", "-q", "tests", "-k", expr], cwd=ROOT, capture_output=True, text=True, timeout=300)
        return [l for l in r.stdout.strip().splitlines() if l.strip()][-1]
    except Exception:
        return None


def capture_note(b, what):
    if b["live"]:
        return callout("Capture source: live API", f"The plans {what} were generated by <b>{esc(b['model_used'])}</b> on {esc(b['captured_at'])}. "
                       "Pipeline 2 itself never uses AI.", "ok", PW)
    return callout("Capture note - please read",
                   f"This machine has no API key, so the plans {what} were written by <b>fake-test-model</b>, the project's offline stand-in "
                   "(<font name='Mono'>tests/fake_llm.py</font>). Pipeline 2 - everything this document is about - is the real, unmodified code and never uses AI. "
                   "<b>Before submission run <font name='Mono'>python -m src.evidence.build_validation_evidence --live</font> with your OPENAI_API_KEY set</b>; "
                   "both documents are regenerated from real model output.", "warn", PW)


def status_bar(counts, width=493):
    total = sum(counts.values()) or 1
    d = Drawing(width, 34)
    x = 0
    order = ["Verified", "Verified with Warning", "Partially Verified", "Manual Review Required", "Contradiction Detected",
             "Unsupported Requirement", "Source Support Missing", "Outdated Source", "Requirement Missing", "Optional Not Included"]
    fills = {"ok": GREEN, "info": GOLD, "warn": RED, "note": BLUE}
    for k in order:
        v = counts.get(k, 0)
        if not v:
            continue
        w = width * v / total
        d.add(Rect(x, 14, w, 16, fillColor=fills[STATUS_KIND[k]] if k != "Optional Not Included" else LINE, strokeColor=colors.white, strokeWidth=0.8))
        if w > 38:
            d.add(String(x + 4, 19, f"{v}", fontName="Sans-B", fontSize=7.5, fillColor=colors.white))
        x += w
    d.add(String(0, 2, "  ".join(f"{k}: {counts[k]}" for k in order if counts.get(k)), fontName="Sans", fontSize=6.8, fillColor=MUTED))
    return d


# =============================================================================== Deliverable 5
def build5(b):
    ag, mx, base, dm = b["extraction_agreement"], b["matrix"], b["baseline"], b["demos"]
    bs = base["scores"]
    rules = b["rules"]

    def cover(c, doc):
        draw_cover(c, doc, "", ["Python Validation", "Pipeline Evidence"],
                   "Pipeline 2 checks every plan the AI writes against rules taken from the documents, in plain Python. This document shows each check "
                   "catching a real problem, with the validator's own output.",
                   [("Deliverable", "5 of 18  -  Python Validation Pipeline Evidence (SRS 1.10)"), ("Pipeline", "Pipeline 2  -  Python only, no Generative AI"),
                    ("Document set", f"Sitara Bank pack  -  {len(b['ingest'])} files, {b['chunks']['total']} clauses"),
                    ("Plans generated with", b["model_used"] + ("  (live API)" if b["live"] else "  (offline stand-in)")),
                    ("Captured on", b["captured_at"])], "Deliverable 5")

    st = [NextPageTemplate("port"), PageBreak(), P("Contents", "h1"), GoldRule(), Spacer(1, 6), make_toc(), PageBreak()]
    # ---------------- 1
    st += H1("1. Evidence at a glance")
    st.append(P("SRS Section 1.10, item 5 lists ten things the submission must demonstrate. Everything below was produced by running the project's real code "
                "(<font name='Mono'>role_matrix/</font>, <font name='Mono'>python_validation/</font>, <font name='Mono'>hallucination_checks/</font>, "
                "<font name='Mono'>contradiction_checks/</font>, <font name='Mono'>schemas/</font>) on the complete Sitara Bank document set.", "body"))
    st += capture_note(b, "used as input in sections 4-11")
    st.append(stat_cards([(mx["total"], "requirements extracted"), (f"{round(100 * ag['obligation'] / ag['compared'])}%", "match answer key"),
                          (f"{sum(r['correct'] for r in b['conflict_vs_key'])}/{len(b['conflict_vs_key'])}", "conflict cases solved"),
                          (len(dm), "defects injected"), (len(dm), "defects caught")]))
    st.append(Spacer(1, 10))
    st.append(table([["SRS item", "Section", "Proof in this document"],
                     ["Requirement extraction", "2", f"{mx['total']} requirements extracted by rules; compared field by field with the team's answer key"],
                     ["Requirement Matrix", "3", f"{mx['active']} active requirements across {len(mx['roles'])} roles; a sample of one role's matrix"],
                     ["Source validation", "4", "A citation to a section that does not exist, and to an adversarial document, are both rejected"],
                     ["Coverage calculation", "5", "Removing four modules drops mandatory coverage and lists every missing requirement"],
                     ["Traceability checking", "6", "Checklist and quiz items with broken citations lower the traceability score"],
                     ["Duplicate detection", "7", "Duplicates in the sources (vs answer key) and in a generated plan are both flagged"],
                     ["Role relevance checking", "8", "A requirement that belongs to another role is sent to manual review"],
                     ["Contradiction handling", "9", "Source conflicts vs answer key; overruled source and changed number caught in a plan; false skip reasons caught"],
                     ["Schema validation", "10", "Seven malformed outputs; six rejected with the exact field, one valid control accepted"],
                     ["Hallucination flagging", "11", "An invented rule and an invented quiz fact are flagged"]],
                    [44 * mm, 16 * mm, 114 * mm]))
    st.append(P("How the demonstrations work", "h2"))
    st.append(P(f"Sections 4 to 11 start from one real plan (<font name='Mono'>{esc(base['plan_id'])}</font>, employee EMP-002, Customer Service Officer). "
                "For each check, one specific defect is written into a copy of that plan and the copy is validated again. Only what is <b>new</b> compared "
                "with the unmodified plan is shown, so each result can be tied to the defect that caused it.", "body"))
    st.append(table([["Baseline plan", "Value"],
                     ["Status", base["status"]], ["Mandatory coverage", f"{bs['coverage']}%  ({bs['mandatory_covered']} of {bs['mandatory_expected']})"],
                     ["Traceability", f"{bs['traceability']}%"], ["Requirement consistency", f"{bs['requirement_consistency']}%"],
                     ["Row results", ", ".join(f"{k}: {v}" for k, v in base["status_counts"].items())]], [60 * mm, 114 * mm]))
    if base["rows_not_verified"]:
        st.append(Spacer(1, 4))
        st.append(P("The baseline is not clean: Pipeline 2 already found these problems in what the model wrote. They are left in place and excluded from each "
                    "demonstration below.", "small"))
        st.append(table([["Requirement", "Status", "Validator explanation"]] +
                        [[r["requirement_id"], badge(r["status"]), r["explanation"]] for r in base["rows_not_verified"]], [30 * mm, 42 * mm, 102 * mm]))

    # ---------------- 2 extraction
    st += [PageBreak()] + H1("2. Requirement extraction")
    st.append(P("Requirements are extracted from document clauses by rules in <font name='Mono'>role_matrix/extractor.py</font> and "
                "<font name='Mono'>config/requirement_rules.yaml</font>. No AI is involved, so the same documents always give the same matrix.", "lead"))
    st.append(table([["Attribute", "Rule"],
                     ["Obligation", "must / shall / required / mandatory = Mandatory; should = Recommended; may = Optional"],
                     ["Requirement type", "From the verb: complete, acknowledge, know, perform, report ..."],
                     ["Applicable roles", "From the section's 'Applies to' line; role names in the clause or document title as fallback"],
                     ["Due stage", "From the deadline wording (Day 1, first week, within N days, end of probation); category default when none"],
                     ["Priority", "From obligation, document criticality (security, privacy, AML, fraud, compliance) and stage"],
                     ["Assessment", "From the requirement type (knowledge quiz, practical, signed acknowledgement ...)"],
                     ["Prerequisites", "'X must be completed before Y' clauses are linked"]], [36 * mm, 138 * mm]))
    st.append(P("Extraction results", "h2"))
    st.append(table([["Obligation", "Requirements"]] + [[k, str(v)] for k, v in b["extraction_by_obligation"].items()], [60 * mm, 40 * mm]))
    st.append(P("Examples of extracted requirements", "h2"))
    rows = [["ID", "Clause", "Extracted attributes"]]
    for s in b["extraction_samples"]:
        roles = "All roles" if len(s["roles"]) >= 12 else ", ".join(s["roles"])
        extra = (f" <font color='#a3372a'>Inactive: overruled by {s['overridden_by']}</font>" if s.get("overridden_by") else "") + \
                (f" <font color='#a3372a'>Inactive: duplicate of {s['duplicate_of']}</font>" if s.get("duplicate_of") else "")
        rows.append([f"<font name='Mono' size='7.4'>{esc(s['requirement_id'])}</font>", s["text"],
                     f"<b>{esc(s['obligation'])}</b> · {esc(s['requirement_type'])} · {esc(s['due_stage'])} · {esc(s['priority'])} priority · "
                     f"{esc(s['assessment'])}<br/>Roles: {esc(roles)}" + (f"<br/>Prerequisite: {esc(', '.join(s['prerequisites']))}" if s.get("prerequisites") else "") + extra])
    st.append(table(rows, [24 * mm, 70 * mm, 80 * mm]))
    st.append(P("Accuracy against the team's answer key", "h2"))
    st.append(P(f"The dataset includes a hand-made answer key (<font name='Mono'>requirements_master.csv</font>, {ag['key_size']} requirements) that was written "
                "independently of the code. Every extracted requirement was compared with it field by field:", "body"))
    c = ag["compared"]
    st.append(table([["Field", "Agree", "Agreement"]] +
                    [[f, f"{ag[k]} / {c}", f"{round(100 * ag[k] / c, 1)}%"] for f, k in
                     [("Requirement found", "compared"), ("Obligation", "obligation"), ("Due stage", "due_stage"), ("Priority", "priority"),
                      ("Applicable roles", "roles"), ("Active / inactive", "active")]], [60 * mm, 40 * mm, 40 * mm], col_style={2: "cellb"}))
    dif = [d for d in ag["differences"] if d["field"] != "presence"]
    if dif:
        st.append(Spacer(1, 6))
        st.append(P(f"The {len(dif)} disagreements, and why", "h3"))
        why = {}
        dup_ids = {d["requirement_id"] for d in b["duplicates_vs_key"]}
        for d in dif:
            if d["field"] == "active" and d["requirement_id"] in dup_ids:
                why[d["requirement_id"]] = "Duplicate of a higher-precedence clause. The application keeps one copy active; the answer key keeps both."
            elif d["field"] == "active" and d["extracted"] is True:
                why[d["requirement_id"]] = "Should have been overruled by a policy (conflict case C09, not detected - see section 9)."
            else:
                why[d["requirement_id"]] = "Different treatment of an overruled or duplicate clause."
        st.append(table([["Requirement", "Field", "Answer key", "Application", "Reason"]] +
                        [[d["requirement_id"], d["field"], str(d["answer_key"]), str(d["extracted"]), why[d["requirement_id"]]] for d in dif],
                        [26 * mm, 18 * mm, 22 * mm, 22 * mm, 86 * mm]))

    # ---------------- 3 matrix
    st += [PageBreak()] + H1("3. Requirement Matrix")
    st.append(P(f"The Role Requirement Matrix is the Python ground truth. Of {mx['total']} extracted requirements, <b>{mx['active']}</b> are active "
                f"({mx['mandatory_active']} mandatory, {mx['role_specific_active']} role-specific). {len(mx['inactive'])} were deactivated because a "
                "higher-precedence source overrules them or they duplicate another clause - they stay in the matrix for traceability but are never expected in a plan.", "body"))
    st.append(table([["Role", "Active requirements", "Mandatory", "Recommended", "Optional", "Role-specific"]] +
                    [[r["role"], r["total"], r["mandatory"], r["recommended"], r["optional"], r["role_specific"]] for r in mx["roles"]],
                    [54 * mm, 28 * mm, 22 * mm, 24 * mm, 20 * mm, 26 * mm]))
    st.append(P("Sample: the first rows of the Customer Service Officer matrix", "h2"))
    st.append(table([["ID", "Requirement", "Obligation", "Stage", "Priority", "Assessment"]] +
                    [[f"<font name='Mono' size='7.2'>{esc(r['requirement_id'])}</font>", r["text"], r["obligation"], r["due_stage"], r["priority"], r["assessment"]]
                     for r in b["matrix_sample"]], [22 * mm, 76 * mm, 19 * mm, 18 * mm, 15 * mm, 24 * mm]))
    st.append(P("Deactivated requirements", "h3"))
    st.append(table([["Requirement", "Reason"]] + [[i["requirement_id"], f"Overruled by {i['overridden_by']}" if i["overridden_by"] else f"Duplicate of {i['duplicate_of']}"]
                                                   for i in mx["inactive"]], [40 * mm, 134 * mm]))

    def demo_section(key, title, lead, verdict_rows=True, issues=True, extra=None):
        d = dm[key]
        out = [PageBreak()] + H1(title)
        out.append(P(lead, "lead"))
        out.append(kv([("Defect written into the plan", d["info"]["changed"]),
                       ("Status after validation", badge(d["status"]) if d["status"] in STATUS_KIND else esc(d["status"])),
                       ("Mandatory coverage", delta(bs["coverage"], d["scores"]["coverage"])),
                       ("Traceability", delta(bs["traceability"], d["scores"]["traceability"]))]))
        out.append(Spacer(1, 6))
        if verdict_rows and d["new_rows"]:
            out.append(P("New requirement-level results", "h3"))
            out.append(table([["Requirement", "Status", "Validator explanation"]] +
                             [[r["requirement_id"], badge(r["status"]), r["explanation"]] for r in d["new_rows"][:18]], [30 * mm, 42 * mm, 102 * mm]))
        if issues and d["new_issues"]:
            out.append(P("New item-level findings", "h3"))
            out.append(table([["Check", "Severity", "Where", "Message"]] +
                             [[i["kind"], i["severity"], i["where"], i["message"]] for i in d["new_issues"][:14]], [34 * mm, 18 * mm, 42 * mm, 80 * mm]))
        if extra:
            out += extra
        return out

    st += demo_section("source_missing", "4. Source validation",
                       "Every cited document and section is looked up in the stored clauses (hallucination_checks/support.py). A citation passes only if the "
                       "section exists in the Active, trusted, non-quarantined version.")
    d2 = dm["source_untrusted"]
    st.append(P("Second case: citing an adversarial document", "h2"))
    st.append(kv([("Defect written into the plan", d2["info"]["changed"]), ("Result", "; ".join(f"{r['requirement_id']}: {r['status']} - {r['explanation']}" for r in d2["new_rows"]))]))
    st.append(Spacer(1, 4))
    st.append(table([["Source check result", "Meaning", "Row status"], ["valid", "Active, trusted section exists", "compared with the matrix"],
                     ["missing", "No such document or section", "Source Support Missing"], ["outdated", "Section exists only in a superseded version", "Outdated Source"],
                     ["untrusted / quarantined", "Adversarial document or quarantined clause", "Unsupported Requirement"]], [40 * mm, 76 * mm, 58 * mm]))

    cov = dm["coverage"]
    miss = [r for r in cov["new_rows"] if r["status"] == "Requirement Missing"]
    st += demo_section("coverage", "5. Coverage calculation",
                       "Coverage = covered mandatory requirements / mandatory requirements expected for the role x 100. A requirement counts only if its "
                       "citation is valid, not overruled, numerically faithful and supported by the source text.", verdict_rows=False,
                       extra=[P("Requirements reported as missing", "h3"),
                              table([["Requirement", "Python expected", "Due stage", "Status"]] +
                                    [[r["requirement_id"], (r.get("python") or {}).get("text", ""), (r.get("python") or {}).get("due_stage", ""), badge(r["status"])] for r in miss],
                                    [28 * mm, 92 * mm, 24 * mm, 30 * mm]),
                              Spacer(1, 6),
                              P(f"Arithmetic: {cov['scores']['mandatory_covered']} covered / {cov['scores']['mandatory_expected']} expected x 100 = "
                                f"<b>{cov['scores']['coverage']}%</b>. The plan status becomes <b>{esc(cov['status'])}</b>; below 100% the Approve button is blocked "
                                "and the reviewer uses <b>Add missing requirements</b>.", "body")])
    st += demo_section("traceability", "6. Traceability checking",
                       "Every checklist item, task and quiz question - not only the covered requirements - must cite a valid source. "
                       "Traceability = items with a valid source / all items x 100.")
    st += demo_section("duplicates", "7. Duplicate detection",
                       "Duplicates are caught at two levels: between source clauses when the matrix is built, and inside a generated plan.",
                       extra=[P("Source-level duplicates vs the answer key", "h3"),
                              table([["Requirement", "Expected duplicate of", "Detected duplicate of", "Correct"]] +
                                    [[d["requirement_id"], d["expected_duplicate_of"], d["detected_duplicate_of"] or "not detected", "Yes" if d["correct"] else "No"]
                                     for d in b["duplicates_vs_key"]], [36 * mm, 46 * mm, 50 * mm, 22 * mm], col_style={3: "cellb"}),
                              Spacer(1, 4),
                              P(f"Plan-level similarity threshold: {rules['duplicate_similarity']} (config/validation_rules.yaml).", "small")])
    rr = dm["role_relevance"]
    st += demo_section("role_relevance", "8. Role relevance checking",
                       "A requirement can be perfectly valid and still wrong for this employee. Anything outside the role's matrix is not counted as coverage and is "
                       "routed to a reviewer.", issues=False,
                       extra=[P(f"Clause added: <i>{esc(rr['info'].get('text', ''))}</i>", "small")])
    ct = dm["contradiction"]
    conflict_rows = [["Case", "Type", "Expected", "Application result", "Rule applied", "Correct"]] + \
                    [[r["case"], r["type"], r["expected"], r["result"], r["rule"], "Yes" if r["correct"] else "No"] for r in b["conflict_vs_key"]]
    solved = sum(r["correct"] for r in b["conflict_vs_key"])
    st += demo_section("contradiction", "9. Contradiction handling",
                       "Contradictions are handled at two levels: conflicting source clauses are resolved by the precedence order when the matrix is built, and a "
                       "plan that cites an overruled clause or changes a number is flagged.",
                       extra=[P("Invalid 'overruled by' claims", "h3"),
                              P("The model may skip a clause only if a higher-authority document overrules it. Python checks every claim:", "body"),
                              table([["Claim written by the model", "Validator finding"]] +
                                    [[i["where"] + " - overruled claim", i["message"]] for i in dm["skip"]["new_issues"] if i["kind"] == "Invalid skip reason"],
                                    [50 * mm, 124 * mm]),
                              CondPageBreak(60 * mm),
                              P(f"Source conflicts vs the answer key: {solved} of {len(b['conflict_vs_key'])} handled correctly", "h3"),
                              table(conflict_rows, [11 * mm, 34 * mm, 26 * mm, 32 * mm, 55 * mm, 16 * mm], col_style={5: "cellb"}),
                              Spacer(1, 4),
                              P("Not detected cases are a known limitation of rule-based detection: they need reasoning without matching numbers or opposite wording "
                                "(for example '60 days' against 'end of probation'). They are listed in the README's limitations.", "small")])
    sc = b["schema_cases"]
    st += [PageBreak()] + H1("10. Schema validation")
    st.append(P("Every GenAI response is validated against the Pydantic schema in <font name='Mono'>schemas/plan_schema.py</font> before anything else. "
                "The same real plan was broken in six different ways; one unchanged copy was included as a control.", "lead"))
    st.append(table([["Case", "Result", "Field", "Pydantic message"]] +
                    [[c["case"], f"<font name='Sans-B' color='{'#2b7a53' if c['result'] == 'accepted' else '#a3372a'}'>{c['result'].title()}</font>",
                      c["errors"][0]["loc"] if c["errors"] else "-", c["errors"][0]["msg"] if c["errors"] else "Valid"] for c in sc],
                    [52 * mm, 20 * mm, 50 * mm, 52 * mm]))
    st.append(Spacer(1, 6))
    st.append(P("A rejected response is never stored. It is retried with the Pydantic message appended to the prompt (see Deliverable 4, section 11).", "body"))
    st += demo_section("hallucination", "11. Hallucination flagging",
                       f"A generated statement must be supported by the clause it cites. Text similarity below {rules['support_similarity_min']} (requirements) or "
                       f"{rules['quiz_support_similarity_min']} (tasks, quizzes), or a number that does not appear in the source, is flagged.")
    st.append(P("Other checks in the validator", "h2"))
    qs = dm["quiz_sequence"]
    st.append(table([["Check", "Finding when a defect was injected"]] + [[i["kind"], i["message"]] for i in qs["new_issues"]] +
                    [["Security scan of the plan", "Instruction-like text in a generated plan is flagged High"], ["Stage spread", f"Warning if more than {int(rules['day1_max_share'] * 100)}% of modules are on Day 1"],
                     ["Rubric weights", "Practical rubrics must add up to 100"]], [46 * mm, 128 * mm]))
    st += [PageBreak()] + H1("12. Automated tests and reproduction")
    tr = b.get("tests5")
    st.append(P("The same checks are asserted by the project's test suite on every run" + (f" - result while building this document: <b>{esc(tr)}</b>." if tr else "."), "body"))
    st.append(table([["Test", "Proves"],
                     ["test_matrix_meets_dataset_minimums", "Extraction meets the SRS dataset minimums"],
                     ["test_faq_conflict_resolved_by_policy", "FAQ loses to policy"], ["test_compliance_conflict_uses_precedence", "Precedence order applied"],
                     ["test_scope_specific_rule_is_not_a_conflict", "General vs role-specific rule both kept"],
                     ["test_duplicates_detected", "Source duplicates found"], ["test_missing_reference_detected", "Missing referenced document found"],
                     ["test_invalid_skip_reasons_are_detected", "False 'overruled by' claims rejected"],
                     ["test_schema_rejects_bad_json", "Schema rejects malformed plans"], ["test_validator_catches_injected_errors", "Hallucination, wrong number, untrusted source, missing requirement caught"],
                     ["test_quiz_and_sequence_errors_flagged", "Quiz answer and sequencing errors caught"],
                     ["test_approval_needs_full_coverage_and_missing_items_can_be_added", "Coverage gate before approval"]],
                    [100 * mm, 74 * mm], col_style={0: "cellm"}))
    st += code("python -m src.evidence.build_validation_evidence            # offline stand-in for plan generation\n"
               "python -m src.evidence.build_validation_evidence --live     # real API from .env\n"
               "python -m pytest -q                                          # the full test suite", label="reproduce")
    doc = ReportDoc(OUT5, "Python Validation Pipeline Evidence - SkillSprint AI", "Deliverable 5  ·  Python Validation Pipeline Evidence", cover)
    doc.multiBuild(st)
    print("written", OUT5)


# =============================================================================== Deliverable 6
def comparison_rows(b):
    out = []
    for p in b["plans"]:
        for r in p.get("rows", []):
            g, py = r.get("genai"), r.get("python")
            st = r["status"]
            if g is None:
                match = "Not generated"
            elif py is None:
                match = "Mismatch"
            else:
                match = "Match" if st == "Verified" and all(r.get("field_matches", {}).values()) else "Mismatch"
            if st == "Requirement Missing":
                cov = "Missing"
            elif st == "Optional Not Included":
                cov = "Not required"
            elif py and py.get("mandatory") and st in ("Verified", "Verified with Warning", "Partially Verified"):
                cov = "Covered"
            elif py and not py.get("mandatory"):
                cov = "Covered (optional)"
            else:
                cov = "Not counted"
            tr = {"valid": "Traced", "missing": "Source not found", "outdated": "Outdated source", "untrusted": "Untrusted source",
                  "quarantined": "Quarantined source"}.get(r.get("source_check"), "-")
            out.append({"Requirement ID": r["requirement_id"], "Role": p["role"],
                        "Source": (py or {}).get("source") or (g or {}).get("source") or "-",
                        "Python expected requirement": (f"{(py or {}).get('text', '')} [{'Mandatory' if py.get('mandatory') else 'Optional'}, {py.get('due_stage')}]" if py else
                                                        (f"Not expected: {r['explanation'].split('Source is ')[-1].rstrip('.')}" if "overridden by" in (r.get("explanation") or "")
                                                         else "Not in this role's matrix")),
                        "GenAI result": (f"{'Mandatory' if g.get('mandatory') else 'Optional'}, {g.get('due_stage')}, cites {g.get('source')} ({r.get('module_id')})" if g else "Not generated"),
                        "Match/Mismatch": match, "Coverage status": cov, "Traceability status": tr, "Validation status": st,
                        "Explanation of disagreement": r.get("explanation") or ("-" if match == "Match" else "")})
    return out


def build6(b):
    rows = comparison_rows(b)
    plans = [p for p in b["plans"] if "rows" in p]
    total = len(rows)
    mc = Counter(r["Match/Mismatch"] for r in rows)
    vc = Counter(r["Validation status"] for r in rows)

    import pandas as pd
    with pd.ExcelWriter(OUT6X, engine="openpyxl") as xw:
        pd.DataFrame(rows).to_excel(xw, index=False, sheet_name="Comparison")
        pd.DataFrame([{"Role": p["role"], "Employee": p["employee_id"], "Plan": p["plan_id"], "Rows": len(p["rows"]), "Coverage %": p["scores"]["coverage"],
                       "Traceability %": p["scores"]["traceability"], "Plan status": p["status"]} for p in plans]).to_excel(xw, index=False, sheet_name="Summary by role")
        ws = xw.sheets["Comparison"]
        for col, w in zip("ABCDEFGHIJ", (16, 22, 16, 60, 46, 14, 16, 18, 22, 50)):
            ws.column_dimensions[col].width = w
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = ws.dimensions

    def cover(c, doc):
        draw_cover(c, doc, "", ["GenAI and Python", "Comparison Report"],
                   f"{total:,} requirement-level results from {len(plans)} roles: what the AI generated, what the Python ground truth expected, "
                   "whether they agree, and why they differ when they do not.",
                   [("Deliverable", "6 of 18  -  GenAI and Python Comparison Report (SRS 1.10)"), ("Results compared", f"{total:,}  (SRS minimum: 100)"),
                    ("Roles", f"{len(plans)} roles, one employee each"),
                    ("GenAI model", b["model_used"] + ("  (live API)" if b["live"] else "  (offline stand-in)")), ("Captured on", b["captured_at"])], "Deliverable 6")

    st = [NextPageTemplate("port"), PageBreak(), P("Contents", "h1"), GoldRule(), Spacer(1, 6), make_toc(), PageBreak()]
    st += H1("1. Summary")
    st.append(P(f"For each of the {len(plans)} roles, one employee's plan was generated by Pipeline 1 (GenAI) and checked by Pipeline 2 (Python). Every "
                "requirement the AI generated, and every requirement the Python matrix expected, produced one row. The SRS asks for at least 100 compared "
                f"results; this report has <b>{total:,}</b>.", "body"))
    st += capture_note(b, "compared in this report")
    st.append(stat_cards([(f"{total:,}", "results compared"), (mc.get("Match", 0), "match"), (mc.get("Mismatch", 0), "mismatch"),
                          (mc.get("Not generated", 0), "not generated"), (f"{round(100 * mc.get('Match', 0) / max(1, total - vc.get('Optional Not Included', 0)), 1)}%", "agreement")]))
    st.append(Spacer(1, 8))
    st.append(P("Validation status of all results", "h3"))
    st.append(status_bar(vc))
    st.append(P("Definitions", "h2"))
    st.append(table([["Column", "Meaning"],
                     ["Python expected requirement", "The requirement text, obligation and due stage in the Role Requirement Matrix (built from documents by rules, no AI)"],
                     ["GenAI result", "What the generated plan said: mandatory or optional, due stage, the source it cited, and the module"],
                     ["Match/Mismatch", "Match = the status is Verified and obligation, source document, section and due stage all agree. Not generated = expected but absent"],
                     ["Coverage status", "Covered, Missing, Not required (optional item not included) or Not counted (failed a check)"],
                     ["Traceability status", "Result of looking up the cited source: Traced, Source not found, Outdated, Untrusted, Quarantined"],
                     ["Validation status", "Pipeline 2's verdict for the row (Verified, Contradiction Detected, Requirement Missing ...)"],
                     ["Explanation of disagreement", "The validator's own reason, written when the two pipelines disagree"]], [46 * mm, 128 * mm]))
    st += [PageBreak()] + H1("2. Results by role")
    rows_role = [["Role", "Employee", "Results", "Match", "Mismatch", "Not gen.", "Coverage", "Trace.", "Status"]]
    for p in plans:
        rr = [r for r in rows if r["Role"] == p["role"]]
        c = Counter(r["Match/Mismatch"] for r in rr)
        rows_role.append([p["role"], p["employee_id"], len(rr), c.get("Match", 0), c.get("Mismatch", 0), c.get("Not generated", 0),
                          f"{p['scores']['coverage']}%", f"{p['scores']['traceability']}%", p["status"]])
    rows_role.append(["<b>Total</b>", "", f"<b>{total}</b>", f"<b>{mc.get('Match', 0)}</b>", f"<b>{mc.get('Mismatch', 0)}</b>", f"<b>{mc.get('Not generated', 0)}</b>", "", "", ""])
    st.append(table(rows_role, [36 * mm, 18 * mm, 15 * mm, 13 * mm, 17 * mm, 15 * mm, 17 * mm, 15 * mm, 28 * mm]))
    st.append(P("Validation status by role", "h2"))
    kinds = [k for k in ["Verified", "Verified with Warning", "Partially Verified", "Contradiction Detected", "Requirement Missing", "Unsupported Requirement",
                         "Source Support Missing", "Outdated Source", "Manual Review Required", "Optional Not Included"] if vc.get(k)]
    short = {"Verified with Warning": "Warn.", "Partially Verified": "Partial", "Contradiction Detected": "Contra.", "Requirement Missing": "Missing",
             "Unsupported Requirement": "Unsupp.", "Source Support Missing": "No source", "Outdated Source": "Outdated", "Manual Review Required": "Manual",
             "Optional Not Included": "Opt. excl."}
    t = [["Role"] + [short.get(k, k) for k in kinds]]
    for p in plans:
        c = Counter(r["Validation status"] for r in rows if r["Role"] == p["role"])
        t.append([p["role"]] + [c.get(k, 0) for k in kinds])
    st.append(table(t, [44 * mm] + [130 * mm / len(kinds)] * len(kinds)))
    st.append(P("Abbreviations: " + "; ".join(f"{v} = {k}" for k, v in short.items() if k in kinds), "small"))

    st += [PageBreak()] + H1("3. Disagreements explained")
    dis = [r for r in rows if r["Match/Mismatch"] != "Match" and r["Validation status"] != "Optional Not Included"]
    reasons = Counter()
    for r in dis:
        e = r["Explanation of disagreement"]
        key = e.split(" by ")[0] if "overridden by" in e else (e.split("(")[0].strip() if e else r["Validation status"])
        reasons[(r["Validation status"], key)] += 1
    st.append(P(f"{len(dis)} results disagree (optional items the AI chose not to include are excluded). They fall into these groups:", "body"))
    st.append(table([["Validation status", "Reason", "Count"]] + [[badge(s), k, n] for (s, k), n in reasons.most_common()], [46 * mm, 108 * mm, 20 * mm]))
    st.append(Spacer(1, 6))
    st.append(P("What the groups mean", "h2"))
    st += bullets(["<b>Contradiction Detected - source is overridden:</b> the AI cited a clause that loses a precedence conflict (usually an FAQ or older SOP). Python replaces "
                   "it with the winning source; the reviewer sees both.",
                   "<b>Verified with Warning - due stage differs:</b> the requirement is right but scheduled in a different stage than the matrix expects.",
                   "<b>Requirement Missing:</b> a mandatory requirement the AI did not include; coverage drops and approval is blocked until it is added.",
                   "<b>Unsupported / Source not found:</b> the AI's text or citation cannot be matched to an approved clause - a possible hallucination."])
    st.append(P("Every disagreement", "h2"))
    st.append(table([["Req ID", "Role", "Python expected", "GenAI result", "Status", "Explanation"]] +
                    [[f"<font name='Mono' size='7'>{esc(r['Requirement ID'])}</font>", r["Role"], r["Python expected requirement"], r["GenAI result"],
                      badge(r["Validation status"]), r["Explanation of disagreement"]] for r in dis],
                    [20 * mm, 22 * mm, 44 * mm, 32 * mm, 24 * mm, 32 * mm], pad=3))

    st += [NextPageTemplate("land"), PageBreak()] + H1("4. Complete comparison table")
    st.append(P(f"All {total:,} results, grouped by role. The same table is supplied as an Excel workbook with filters "
                "(<font name='Mono'>reports/Deliverable_6_GenAI_vs_Python_Comparison_Report.xlsx</font>).", "body"))
    for p in plans:
        rr = [r for r in rows if r["Role"] == p["role"]]
        st.append(CondPageBreak(40 * mm))
        st.append(Heading(f"{esc(p['role'])}  ·  {p['employee_id']}  ·  {len(rr)} results", 1, "h3"))
        st.append(table([["Req ID", "Source", "Python expected requirement", "GenAI result", "Match", "Coverage", "Traceability", "Validation status", "Explanation"]] +
                        [[f"<font name='Mono' size='6.8'>{esc(r['Requirement ID'])}</font>", r["Source"], r["Python expected requirement"], r["GenAI result"],
                          r["Match/Mismatch"], r["Coverage status"], r["Traceability status"], badge(r["Validation status"]), r["Explanation of disagreement"]] for r in rr],
                        [20 * mm, 18 * mm, 72 * mm, 46 * mm, 17 * mm, 19 * mm, 19 * mm, 25 * mm, 33 * mm], pad=2.5))
    doc = ReportDoc(OUT6, "GenAI and Python Comparison Report - SkillSprint AI", "Deliverable 6  ·  GenAI and Python Comparison Report", cover)
    doc.multiBuild(st)
    print("written", OUT6)
    print("written", OUT6X)


if __name__ == "__main__":
    if "--rebuild" in sys.argv:
        bundle = json.load(open(capture_validation.OUT, encoding="utf-8"))
    else:
        bundle = capture_validation.capture("--live" in sys.argv)
    bundle["tests5"] = run_tests("matrix or schema or validator or quiz or approval or skip")
    build5(bundle)
    build6(bundle)
